name: myapp

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Unit test
        run: |
          go mod init app
          go test .

      - name: Build 
        run: |
          go build -o app main.go

      - name: Archive Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app
      
      - name: Deploy
        run: |
          sh "ssh-keyscan 192.168.105.3 > ~/.ssh/known_hosts"

          echo "${{ secrets.SSH__KEY }}" > ~/.ssh/my_key

          sh "ssh -l vagrant -i ~/.ssh/my_key 192.168.105.3 -C sudo systemctl stop myapp || true"

          sh "scp -i ~/.ssh/my_key app vagrant@192.168.105.3:"
          sh "scp -i ~/.ssh/my_key myapp.service vagrant@192.168.105.3:"

          sh "ssh -l vagrant -i ~/.ssh/my_key 192.168.105.3 -C sudo mv myapp.service /etc/systemd/system/"
          sh "ssh -l vagrant -i ~/.ssh/my_key 192.168.105.3 -C sudo systemctl daemon-reload"
          sh "ssh -l vagrant -i ~/.ssh/my_key 192.168.105.3 -C sudo systemctl start myapp"
          sh "ssh -l vagrant -i ~/.ssh/my_key 192.168.105.3 -C sudo systemctl enable myapp"