name: myapp

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Unit test
        run: |
          go mod init app
          go test .

      - name: Build 
        run: |
          go build -o app main.go

      - name: Archive Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app