name: myapp

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Unit tests
        run: |
          go mod init app
          go test .
