name: myapp

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Unit test
        run: |
          go mod init app
          go test .

      - name: Build 
        run: |
          go build -o app main.go

      - name: Archive Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app
      
      - name: Deploy
        run: |
          ssh-keyscan 192.168.105.3 > ~/.ssh/known_hosts

          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/my_key && chmod 600 ~/.ssh/my_key

          ssh -l vagrant -i ~/.ssh/my_key 192.168.105.3 -C sudo systemctl stop myapp || true

          scp -i ~/.ssh/my_key ${{ github.workspace }}/app vagrant@192.168.105.3:
          scp -i ~/.ssh/my_key myapp.service vagrant@192.168.105.3:

          ssh -l vagrant -i ~/.ssh/my_key 192.168.105.3 -C sudo mv myapp.service /etc/systemd/system/
          ssh -l vagrant -i ~/.ssh/my_key 192.168.105.3 -C sudo systemctl daemon-reload
          ssh -l vagrant -i ~/.ssh/my_key 192.168.105.3 -C sudo systemctl start myapp
          ssh -l vagrant -i ~/.ssh/my_key 192.168.105.3 -C sudo systemctl enable myapp